# Generated by Django 4.2.6 on 2023-11-03 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_user_alter_contact_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('all_images', models.ImageField(default='profile.png', upload_to='images')),
            ],
        ),
    ]
