# Generated by Django 4.2.6 on 2023-11-03 19:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_hero_text4'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='text5',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
