# Generated by Django 4.2.6 on 2023-11-03 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_hero_text5'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hero',
            old_name='all_images',
            new_name='image_url',
        ),
    ]
