# Generated by Django 4.2.6 on 2023-11-03 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_rename_all_images_hero_image_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hero',
            old_name='image_url',
            new_name='heroimage',
        ),
    ]
