# Generated by Django 4.2.6 on 2023-11-05 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_services_rename_text1_about_about_des_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='services_des',
        ),
    ]
