# Generated by Django 4.2.6 on 2023-11-05 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_blog_contact_contact_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='shop_image',
            field=models.ImageField(default='profile.png', upload_to='images'),
        ),
    ]
