# Generated by Django 4.2.6 on 2023-11-05 19:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_shop_shop_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crafted', models.CharField(max_length=100)),
                ('crafted_des', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='shop',
            name='image1name',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shop',
            name='image1price',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shop',
            name='image2name',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shop',
            name='image2price',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shop',
            name='image3name',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shop',
            name='image3price',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shop',
            name='shop_image1',
            field=models.ImageField(default='profile.png', upload_to='images'),
        ),
        migrations.AddField(
            model_name='shop',
            name='shop_image2',
            field=models.ImageField(default='profile.png', upload_to='images'),
        ),
        migrations.AddField(
            model_name='shop',
            name='shop_image3',
            field=models.ImageField(default='profile.png', upload_to='images'),
        ),
    ]
