# Generated by Django 4.2.6 on 2023-11-05 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_home_shop_image1name_shop_image1price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='shop_image',
        ),
    ]
